- hosts: all
  become: yes
  tasks:
  - name: "APT - Add Docker GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "APT - Add Docker repository"
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      filename: docker

  - name: "APT - install misc packages"
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - "aptitude"
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "software-properties-common"

  - name: "APT - install 'docker-ce'"
    apt:
      name: "docker-ce"
      update_cache: yes

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  - name: install kubelet
    apt:
      name: kubelet
      state: present
      update_cache: true

  - name: install kubeadm
    apt:
      name: kubeadm
      state: present

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       state: present
       force: yes
